### ISSUE TITLE
partner logos

### ISSUE THREAD

**Issue by loomis** [cyclone-project/cyclone-tracking#1]
As a CYCLONE participant, I can find the high-resolution logos for each partner in the project's document repository.

**Comment by ydemchen** [comment]
![uva-logo](https://cloud.githubusercontent.com/assets/10939202/6126164/ebc2c572-b11d-11e4-897b-d4a13ad03c42.png)

**Comment by loomis** [comment]
@ydemchen Thanks for providing the UvA logo.  The ticket is for all partners, so I'm reopening the ticket.

**Comment by lodygens** [comment]
Laboratoire de l'Accélérateur Linéaire
![logolal](https://cloud.githubusercontent.com/assets/6367731/6126901/5e3493fe-b125-11e4-8d74-902152e9d180.jpg)

**Comment by lodygens** [comment]
CNRS :
![in2p3-q_signv](https://cloud.githubusercontent.com/assets/6367731/6126965/2078b396-b126-11e4-9596-09c21b190151.jpg)

**Comment by Josyab** [comment]
I2CAT: 
![logo-i2cat](https://cloud.githubusercontent.com/assets/4611375/6128774/3026adda-b139-11e4-92be-c1beee01e39b.jpg)

**Comment by loomis** [comment]
The partner logos should be uploaded to the shared folder in ZettaBox in `Media/Logos/Partner`.  Create files with the partner short name as the first element.  If possible provide both a vector version of the logo and a high-resolution bitmap version.

Vector Logo:
- [ ] Interoute
- [ ] SixSq
- [ ] QSC
- [ ] TUB
- [ ] i2CAT
- [ ] UvA
- [ ] CNRS

Bitmap Logo:
 - [ ] Interoute
 - [ ] SixSq
 - [ ] QSC
 - [ ] TUB
 - [ ] i2CAT
 - [ ] UvA
 - [ ] CNRS

**Comment by Josyab** [comment]
I2CAT provided the vector format logo

**Comment by cblanchet** [comment]
Here are the logo for CNRS and IFB (I don't think that the CNRS-IN2P3 logo is necessary). Waiting the invitation to join the zettabox to be able to upload the requested formats. 

CNRS 
![com_cnrsfr-grandrvb](https://cloud.githubusercontent.com/assets/1726436/6171185/aedbbc3c-b2d9-11e4-8aa0-893bb18546c9.jpg)

IFB 
![logo-ifb_png](https://cloud.githubusercontent.com/assets/1726436/6171484/3d12dac0-b2db-11e4-847a-0c4c7fd7917d.jpg)

**Comment by lodygens** [comment]
I should have scalable CNRS and LAL logos next week

**Comment by lodygens** [comment]
CNRS and LAL logo uploaded into Zettabox in PDF versions.

**Comment by Josyab** [comment]
All of the partner logos are available in ZettaBox in Media/Logos/Partner. This can be closed
