### ISSUE TITLE
participant contact information

### ISSUE THREAD

**Issue by loomis** [cyclone-project/cyclone-tracking#10]
As a CYCLONE participant, I can find the list of GitHub IDs for all of the project participants.

**Comment by lodygens** [comment]
"lodygens"

**Comment by Josyab** [comment]
"josyab"

**Comment by cblanchet** [comment]
cblanchet

**Comment by loomis** [comment]
Provide the personal information in the `cyclone-directory.xlsx` spreadsheet in the ZettaBox `General` directory.

**Comment by lodygens** [comment]
Since I can only have access to Zettabox through the Web interface, I upload a modified copy of the document to not overwrite the shared one.

**Comment by cblanchet** [comment]
updated for CNRS IFB and uploaded in zettabox folder
