### ISSUE TITLE
i2CAT to investigate on Query languages

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-tracking#103]
I2CAT will internally figure out which type of QUERY languages are more familiar with (RDF( fileformat, XML standard), SQL (data based related), Classadds (to make service matching),  CUSTOM DSL, etc. 

The outcome is a selection on the QUERY language.

**Comment by mathiasslawik** [comment]
I thought "Query Language" pertains Slipstream and the Broker and therefore TUB...

**Comment by Josyab** [comment]
Hi Mathias, 

In Orsay we discussed about this Query languages and it´s true that pertains to SlipStream and the Broker. But also we may be including some policies which attain to the networking aspects while deploying applications. As far as i could understood, Slipstream could deploy applications according to some policies (including brokering, networking policies) so that also from the networking side it is important to take into account these QUERY LANGUAGES. 

This doesn´t mean that we (i2CAT) is deciding the type of QUERY LANGUAGES which is more suitable. Indeed it is more likely that Slipstream and TUB broker have more to say on this. But still, we would like to internally indentify  if we have experience on any of them, so that in case you (CYCLONE partners) are also familiar, we can go for this option.

**Comment by Josyab** [comment]
No longer relevant. I close it
