### ISSUE TITLE
Security Infrastructure (D4.1): Detail bioinformatics use case communication protocol for end-to-end security

### ISSUE THREAD

**Issue by mathiasslawik** [cyclone-project/cyclone-tracking#106]
We did propose to use TCTP for end-to-end security, yet TCTP only addresses issues arising within HTTP(S) based communication. We would need to analyse other protocols in order to secure other communication protocols.

The bioinformatics use case description should be extended by information regarding the communication protocol used for end-to-end communication.

This relates to #70.

**Comment by mathiasslawik** [comment]
Christophe and I talked about this topic.

There are two different communication protocols for uploading data to the VMs: either by using an upload form rendered on the VM or by using secure transfer, e.g., SCP/SFTP.

We can use TCTP to secure the HTTP upload to the VMs.

Christophe will write down information about how cloud application users will upload data to the VMs.

**Comment by cblanchet** [comment]
To details the needs.

We use scp/sftp mainly
- to ensure AuthN/Z for the data transfer
- to overcome the performance issues for large dataset
- and to transfer data from a remote server with only a CLI.

If HTTP with TCTP can satisfy all the points, we can use it for all end-to-end communications

**Comment by mathiasslawik** [comment]
This is now clear enough for me.
