### ISSUE TITLE
Integrate CYCLONE Federation Provider with Apache HTTP server

### ISSUE THREAD

**Issue by mathiasslawik** [cyclone-project/cyclone-tracking#112]
The bioinformatics portal is implemented using Django on Apache and relies on the Apache environment variables (e.g. REMOTE_USER) as the source of the authenticated user identity.

We should integrate the CYCLONE Federation Provider with Apache so that the user identity can be passed to applications running on top of the HTTP server.

This relates to #74.

**Comment by mathiasslawik** [comment]
There is an Apache module which should allow OpenID Connect login, and therefore Keycloak login:

https://github.com/pingidentity/mod_auth_openidc

@lodygens: Do you want to experiment with the module and try out if you can get it to work with our Federation Provider?

**Comment by lodygens** [comment]
dear Mathias,
I would be glad to test all that.
As far as I understand, Apache modules should be considered on server side only and we don't use Apache for Stratuslab; Apache modules must definitly not concern end users.

Can you please clarify the testing scenario you have in mind?
:)

**Comment by mathiasslawik** [comment]
This ticket is about the bioinformatics portal. Maybe I misunderstood you, but didn't you tell me, that the portal is implemented using Django on Apache?

**Comment by lodygens** [comment]
I know nothing about this portal; maybe Christophe could give us some details...

**Comment by cblanchet** [comment]
We are using standard Apache attributes about group membership. Here is the rules we put in the pilot.

    <Location /test>
        AuthType shibboleth
        ShibRequestSetting requireSession true
        require isMemberOf testGroup
    </Location>

**Comment by mathiasslawik** [comment]
We published a demo for integrating the Federation Provider with Apache2:

https://github.com/cyclone-project/cyclone-federation-provider-apache-oidc-demo

Please, try it out and just contact us if it works for you or not.

**Comment by mathiasslawik** [comment]
Done and demonstrated.

**Comment by lodygens** [comment]
Dear Matthias,
I am checking OpenStack Keystone and OAuth just to see how it works and how deep it fullfills Cyclone needs.
Thank for providing a Docker container, it is a great help.
But the way, I wonder why you did not configure all that with HTTP only, and not HTTPS...


Thanks


```root@d39051a5fb76:/etc/apache2# more mods-enabled/auth_openidc.load 
LoadModule auth_openidc_module /usr/lib/apache2/modules/mod_auth_openidc.so
root@d39051a5fb76:/etc/apache2# dir /usr/lib/apache2/modules/mod_auth_openidc.so ^C
root@d39051a5fb76:/etc/apache2# more sites-enabled/000-default.conf 
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    OIDCRedirectURI http://localhost:8080/example/redirect_uri
    OIDCCryptoPassphrase **NOT**SHOWN**IN**GITHUB** :) **
    OIDCClientID slipstream
    OIDCClientSecret **NOT**SHOWN**IN**GITHUB** :) **
    OIDCProviderMetadataURL https://federation.cyclone-project.eu/auth/realms/master/.well-known/openid-configuration

    <Location /example/>
        AuthType openid-connect
        Require valid-user
    </Location>
</VirtualHost>
root@d39051a5fb76:/etc/apache2# ```

**Comment by lodygens** [comment]
Another question: how can we use more than one IdP?
Thanks
