### ISSUE TITLE
Get Shibboleth attributes into identity token of CYCLONE Federation Provider

### ISSUE THREAD

**Issue by mathiasslawik** [cyclone-project/cyclone-tracking#113]
The future Bioinformatcs cloud portal authorization should rely on some Shibboleth attributes. It should be evaluated how we can get those attributes into the identity token of the Federation Provider.

This relates to #74.

**Comment by lodygens** [comment]
As far as I know, JWT standard includes extensions. It is finally the middleware responsibility to check expected attributes in the provided token.

**Comment by lodygens** [comment]
Then, of course, it is very important to know which attributes Bioinformatics applications need.

**Comment by mathiasslawik** [comment]
Our preliminary list of available user information which are mapped into the token:

* Their unique user identifier (eduPersonPrincipalName)
* The relationship(s) to their institution (eduPersonAffiliation)
* Their preferred name when displaying entries (displayName)
* Their home organization’s domain name (schacHomeOrganization)

**Comment by mathiasslawik** [comment]
We're getting the attributes, but there are some bugs left.
