### ISSUE TITLE
Consolidate CYCLONE Semester Report #1

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-tracking#115]
as discussed in last meeting at LAL and further requested by our PO, we need to provide a technical Semester Report of our project activities and major achievements for the period Jan-Jun/2015.

Please follow the following plan of action:

1.- All partners: provide inputs per WP by 30-Jun-2015 EOB
2.-  WP leaders:  consolidate the WP summary by 3-Jul-15 EOB
3.- IRT & I2CAT: consolidate report by 10-Jul-2015 noon and send to EC/PO

Based on this agreement Matteo reached with our PO and our previous experience with such reports, we've prepared a template you can find in OneDrive at the following location

CYCLONE    WP1
 - Management    SemesterReports    CYCLONE_SR-2015-Jan-Jun-v0.1.docx

**Comment by lodygens** [comment]
dear Jose
are we not supposed to have the weekly meeting at 10:00?

thanks

Oleg Lodygensky
Laboratoire de l'Accelerateur Lineaire
Universite Paris Sud 11
Bat 200
91898 Orsay Cedex
France

Tél +33 (0)1 64 46 82 75
Mobile +33 (0)6 52 85 71 21
Fax +33 (0)1 69 07 94 04
email : oleg.lodygensky@lal.in2p3.fr
Web : http://www.xtremweb-hep.org

**Comment by mathiasslawik** [comment]
I've included some items from TUB and will talk to Ilke on monday if we have more to report.

I would propose structuring the report on the work into a "general WP related" section and then sections relating to the specific tasks of the WP from the DoA. I've included these sections into the document. Feel free to delete them if you find them inappropriate.

I think it would lead to a more stuctured look and we would make it more clear how we relate our work done to the work planned.

**Comment by Interoute123** [comment]
All, 

please mark any addition/revision to the SR document under track change mode

**Comment by cblanchet** [comment]
I uploaded the consolidated WP3 summary in Onedrive (file CYCLONE_SR-2015-Jan-Jun-v0.2_WP3.docx)

**Comment by Interoute123** [comment]
The final Cyclone Semester Report has been  uploaded on OneDrive at the following link:

https://onedrive.live.com/view.aspx?cid=2c3033fe409659bd&page=view&resid=2C3033FE409659BD!464&parId=2C3033FE409659BD!423&app=Word
