### ISSUE TITLE
Investigate keycloak

### ISSUE THREAD

**Issue by lodygens** [cyclone-project/cyclone-tracking#116]
Keycloak (http://keycloak.jboss.org) is an SSO and IDM integrator for browser apps and RESTful web services based on OAuth 2.0, Open ID Connect, JSON Web Token (JWT) and SAML 2.0 specifications.

We must investigate this middleware to see how to integrate to Cyclone WP4.

**Comment by lodygens** [comment]
As described in Jun 22 2015 rendez minutes (stored in onedrive/cylcone/wp4/rendezvousminutes/20150622.doc), keycloak does not support X509 certificates. 
We should investigate how important it would be to enable X509 certificate usage.

**Comment by mathiasslawik** [comment]
Keycloak is used as a Federation Provider and not as an Identity Provider, i.e., your local Identity Provider and not Keycloak has to support X509 login. If, as I think, people already authenticate to EduGAIN via X509, they can be used to also authenticate via Keycloak, as Keycloak just maps the issued SAML tokens to JSON web tokens.

**Comment by lodygens** [comment]
Great! I understand.

By the way, I have found a web site proposing SAML tutorials and tools:
 https://www.samltool.com/online_tools.php

Hope his helps

**Comment by lodygens** [comment]
I must say that I don't really see the Keycloak usefulness : we already know how to federate identities as described in Keycloak documentation, chapter 9.

It's not hard (and already developped) to propose several identity mechanisms and providers:
+ OAuth/OpenID 2.0 : Google, Facebook etc.
+ X509 and CA certification paths (as many as wished)
- the only missing is Shibboleth/SAML.

In Keyclaok dashboard, we can configure a SAML Identity Provider. 
But this leads exactly to the problems I have with my developments: properly configure a Shibooleth IdP
:)

Maybe I should propose a demo so that we can discuss the opportunity to use keycloak or not

**Comment by mathiasslawik** [comment]
I don't think I understand you. Are you proposing that we do not use Keycloak and write a whole Federation Provider / Identity Broker by ourselves? Or do you propose an alternative architecture without an Identity Broker / Federation Provider?

**Comment by lodygens** [comment]
My only point is that we will finally use Keycloak for Shibboleth/ASML only
(as far as I understand)

**Comment by mathiasslawik** [comment]
It's investigated thoroughly.
