### ISSUE TITLE
SSH connection using federated identity

### ISSUE THREAD

**Issue by lodygens** [cyclone-project/cyclone-tracking#117]
dear all,
in #82, Christophe introduces the Moonshot project (https://community.jisc.ac.uk/groups/moonshot) that seems to propose a solution to connect to SSH server using federated identity.

We should glance what they propose and see how this could help our goals, if applicable.

**Comment by lodygens** [comment]
We should especially gnalce at 
https://wiki.moonshot.ja.net/display/Moonshot/General+Account+Mapping+Advice

**Comment by mathiasslawik** [comment]
@cblanchet: Could we also consider another option: The Bioinformatics Users deposit their SSH public keys either in the cloud portal or as a user attribute in their IDP. The cloud portal then uses this public key as a deployment option for slipstream, so that the VMs are deployed having the bioinformatics users public keys authorized for root access.

**Comment by lodygens** [comment]
but then, keep in mind that, inside the VM, the user won't have access to services that need federated identity
cheers

**Comment by mathiasslawik** [comment]
The users can still authenticate to external federated services even if they logged onto the machine via SSH, just like they would if they would be working locally. They'd just start the authentication process on the remote machine.

**Comment by lodygens** [comment]
I'm not sure this is always possible/desirable: users may not want to copy their X509 private key to VM for security reasons (not mentionning they may not know how to do that)

**Comment by cblanchet** [comment]
The users of the IFB's cloud are already providing their SSH public key in the IFB's dashboard. Then this user key is automatically added to the SSH authorized keys in the user VMs (done by StrausLab).

**Comment by mathiasslawik** [comment]
We created a possible solution idea for this challenge.

Basically, we employ keyboard-interactive mode of SSH and integrate our own PAM module.

This PAM module (e.g. "pam_openid_connect") starts an embedded web server and displays a URL to the user in the interactive shell, which they should click to authenticate via the federation provider. The web server returns to the PAM subsystem if the user logged on successfully or not. This is based on a list of allowed users, which the VM should get via SlipStream.

**Comment by lodygens** [comment]
well done :)

**Comment by ilke-zilci** [comment]
A basic implementation of the PAM module has been deployed on LAL. The ssh login for an existing user works. Follow up open issues in [#189](https://github.com/cyclone-project/cyclone-tracking/issues/189) , [#190](https://github.com/cyclone-project/cyclone-tracking/issues/190) and [#191](https://github.com/cyclone-project/cyclone-tracking/issues/191)
