### ISSUE TITLE
Security Infrastructure (D4.1): Create overview diagrams showing the central WP4 aspects

### ISSUE THREAD

**Issue by mathiasslawik** [cyclone-project/cyclone-tracking#118]
You can find the first overview here:
* PDF: https://onedrive.live.com/view.aspx?resid=2C3033FE409659BD!455&app=WordPdf
* Visio: https://onedrive.live.com/?id=2C3033FE409659BD%21453&cid=2C3033FE409659BD

**Comment by lodygens** [comment]
Well done
:+1: 
May I suggest you insert some ordering
e.g.
-1- users present valid credentials
-2- IdPs issue user assertion
-3- FP validates SAML signature
etc.

:)

**Comment by lodygens** [comment]
-A- Stratuslab keeps its authentication/authorization mechanisms: it does not rely on Slipstream.
-A.1- Stratuslab is able to authenticate users from 
 * IdP
 * Certificate Authority
-A.2- Json Web Token (JWT) may be sent to Stratuslab by distributed parties (including Slipstream).
Stratuslab  will verify JWT integrity as described for relying services.

-B- OpenNaaS has not connection mechanism at all (as far as I understand)
I am not sure we can say "Stratuslab is able to connect to OpenNaas"
I would rather write something like "Stratuslab will propose OpenNaaS as a new cloud service; Stratuslab AuthN/AuthZ policy will apply to OpenNaaS access"

**Comment by mathiasslawik** [comment]
Deliverable submitted, closing ticket.
