### ISSUE TITLE
Mailing list people

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-tracking#12]
Please provide the name, surname and mailing list (CYCLONE-tech and/or CYCLONE-admin) to include them.

**Comment by eduesc** [comment]
Emails requested and some answers received. Waiting for UvA and SixSq

**Comment by Josyab** [comment]
UvA and Sixsq mails already received. I will include them and then we will close the cloudfederation mailing list.

**Comment by eduesc** [comment]
Mailing lists created:
Admin: cyclone-admin@i2cat.net
Tech: cyclone-tech@i2cat.net
