### ISSUE TITLE
Extend Slipstream by Federation Provider Authentication

### ISSUE THREAD

**Issue by mathiasslawik** [cyclone-project/cyclone-tracking#124]

**Comment by loomis** [comment]
Depends on #127.

**Comment by lodygens** [comment]
dear all
we are still on rendezvous

can you reconnect (maybe restart your web browser) ?

:)



Oleg Lodygensky
LAL
Université Paris Sud
Bat 200
91898 Orsay Cedex

Tel: +33 1 64 46 82 75
Mobile : +33 6 52 85 71 21
Mail: oleg.lodygensky@lal.in2p3.fr

http://www.xtremweb-hep.org <http://www.xtremweb-hep.org/>
http://openstack.lal.in2p3.fr/ <http://openstack.lal.in2p3.fr/>
http://www.stratuslab.eu <http://www.stratuslab.eu/>
