### ISSUE TITLE
Create a CYCLONE folder in Zettabox 

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-tracking#13]
Create a CYCLONE folder in Zettabox and distribute credentials to partners

**Comment by lodygens** [comment]
I don't find ay shared folder in Zettabox.
Did I miss something? 
:)

**Comment by eduesc** [comment]
Apparently, Zettabox has a bug which does not allow to send the invitation to email address which have the “-” in the body of the address. IRT will raise this issue with their development team, for to resolve this as soon as possible.

The addresses affected are:
xxx@france-bioinformatique.fr
yyy@tu-berlin.de

**Comment by lodygens** [comment]
ah ok
:)

Oleg Lodygensky
Laboratoire de l'Accelerateur Lineaire
Universite Paris Sud 11
Bat 200
91898 Orsay Cedex
France

T�l +33 (0)1 64 46 82 75
Mobile +33 (0)6 52 85 71 21
Fax +33 (0)1 69 07 94 04
email : oleg.lodygensky@lal.in2p3.fr
Web : http://www.xtremweb-hep.org



Le 12 f�vr. 2015 � 14:35, eduesc <notifications@github.com> a �crit :

**Comment by Josyab** [comment]
The CYCLONE folder has been created.

**Comment by lodygens** [comment]
Unde MAc OS 10.9.5:
 - Zettabox crashes every day
 - when Zettabox is running, the synchronzation is very very long

**Comment by loomis** [comment]
@lodygens: I don't think that ZettaBox bugs are part of this issue.  If we want to track these bugs, then we should create separate issues for them.

**Comment by lodygens** [comment]
This was not a bug report, but a shared folder access problem notification.
