### ISSUE TITLE
Define a appliance creation workflow

### ISSUE THREAD

**Issue by lodygens** [cyclone-project/cyclone-tracking#140]
We should write a document defining appliance creation.

Following discussions #132 and #136, it appears that appliance creation in a multi cloud environment needs the definition of a clear process where steps and actors are clearly determined.

**Comment by mathiasslawik** [comment]
This should also go to the website.

**Comment by lodygens** [comment]
Ilke, I would like to start writing (with your help ;) ) this documentation.

-1- What preferred file format? 
 -  . md  ?

-2- Where to store it?
Directly in cyclone-project.github.io ?
But I don't see there any "kind of" repository, I mean there is no "obvious" subdirectory in "cyclone-project.github.io": should I create a "doc" one?

**Comment by ilke-zilci** [comment]
cyclone-project.github.io is primarily for the cyclone website, anything we commit to the master branch is published at cyclone-project.eu, but we can work on a branch with an .md file and it will only be published when we merge it to master.

**Comment by ilke-zilci** [comment]
I created a 'tutorial' branch and added an 'appliance_creation.md' file with a title. The file is now linked to the Media tab submenu, but we can change it later. Please make sure you pull the 'tutorial' branch and that your local tutorial branch tracks origin's tutorial branch.

https://github.com/cyclone-project/cyclone-project.github.io/blob/tutorial/appliance_creation.md

**Comment by lodygens** [comment]
Great, thanks.

**Comment by ilke-zilci** [comment]
I added the roles and responsibilities. The concrete steps depend on the cloud choice.

**Comment by ilke-zilci** [comment]
I added the roles and responsibilities. The concrete steps depend on the cloud choice.

**Comment by ilke-zilci** [comment]
@lodygens Oleg, could you please review the draft on the appliance creation workflow: https://github.com/cyclone-project/cyclone-project.github.io/blob/tutorial/appliance_creation.md

**Comment by lodygens** [comment]
Dear Ilke, I have removed "(on stratuslab)" from "image endorser" line, since :
1. image creation is independant from IaaS;
2. there must be an image endorser whatever its usage to dispatch responsibility: it is the endorser responsibility to regularly update image, correct bugs etc.

:)

**Comment by ilke-zilci** [comment]
done on tutorial branch of the website.
