### ISSUE TITLE
Create Threat Model and Threat Analysis for Security Architecture (D4.1)

### ISSUE THREAD

**Issue by mathiasslawik** [cyclone-project/cyclone-tracking#144]
We should create a Threat Model and Threat Analysis for one or more of the use cases for the Security Architecture Deliverable.

**Comment by lodygens** [comment]
The OpenStack Security Boundaries and Threat can be found here: 
http://docs.openstack.org/security-guide/introduction/security-boundaries-and-threats.html

Hope this helps

**Comment by mathiasslawik** [comment]
Deliverable submitted, closing ticket.
