### ISSUE TITLE
Input for Threat Model and Analysis based on StratusLab

### ISSUE THREAD

**Issue by mathiasslawik** [cyclone-project/cyclone-tracking#145]
Could you please provide us some input for our Threat Model and Analysis?

Maybe you already have a Threat Model or could provide us with some Threats you'd consider relevant for StratusLab.

This relates to #144.

**Comment by lodygens** [comment]
I have uploaded a first version (V0 ;) ) to OneDrive

**Comment by mathiasslawik** [comment]
Great, it looks like it's going in the right direction. I'll include it into D4.1 and give you more feedback when I've looked at it more thoroughly.

**Comment by lodygens** [comment]
updated to v0.1
added "Data Flow Diagram"

**Comment by mathiasslawik** [comment]
I think its OK for now.
