### ISSUE TITLE
Input for Bioinformatics Threat Model and Analysis

### ISSUE THREAD

**Issue by mathiasslawik** [cyclone-project/cyclone-tracking#146]
Could you provide us with some Input for a Bioinformatics Threat Model and Analysis to show some security aspects for the Security Architecture D4.1. This relates to #144.

Maybe you already have a Threat Model or some ideas on the most relevant Security Threats?

**Comment by cblanchet** [comment]
We don't have a threat model.

Main security threats for the bioinformatics use cases are the specific ones related to the data biomedical analysis (the others are the usual ones related to a scientific application):
- unauthorized access to the biomedical data
- the biomedical data are not completely erased from the datacenter when requested by the user (end of the analysis, shutdown of the VM)

**Comment by lodygens** [comment]
Christophe, I think Mathias would appreciate to describe the BioInformatique threat analyse following this documentation: https://www.owasp.org/index.php/Application_Threat_Modeling.
I have done it for Stratuslab in #145 (the document is available in onedrive) and can propose to help you, if needed.

**Comment by mathiasslawik** [comment]
Deliverable submitted, closing ticket.

I think we'll either include this into next years deliverable or change to OpenStack-relevant content.
