### ISSUE TITLE
Milestone M501 - Functional description and initial requirements for OpenNaaS extensions and interfaces

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-tracking#150]
Release M501 by the en of October (M10). @Josyab will provide support.

-Build the ToC.
-Check the ToC internally in I2CAT.
-Provide the full detail on the extensions.
-Review and release.

**Comment by lodygens** [comment]
dear all
is anybody connected ? 

(https://rendez-vous.renater.fr/CYCLONEweekly)


Oleg Lodygensky
LAL
Université Paris Sud 
Bat 200
91898 Orsay Cedex

Tel: +33 1 64 46 82 75
Mobile : +33 6 52 85 71 21
Mail: oleg.lodygensky@lal.in2p3.fr

http://www.xtremweb-hep.org
http://www.stratuslab.eu
