### ISSUE TITLE
Create a CYCLONE flyer for merchandising

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-tracking#16]
Create a CYCLONE flier to create awareness on CYCLONE project. The Flier will firstly be used during a conference that will take place on the 12th of March in the conference during the te

**Comment by Josyab** [comment]
Create a CYCLONE flier to create awareness on CYCLONE project. The Flier will firstly be used during a conference that will take place on the 12th of March iduring the Intercloud2015 workshop. There will a panel at the workshop where UvA  plans to present couple of slides on Cyclone.

**Comment by Josyab** [comment]
Some comments to the current Draft version.

1.- Move the top EC logo to the right corner of the leaflet. 
2.- Expand the header title and put it in the center.
3.- The proposed sections are fine to me.
4.- The sentence: "Application service providers (ASPs) develop, deploy, and maintain complex computing platforms within multiple cloud infrastructures to improve resilience, responsiveness and elasticity of their applications" and the next one should be together in the same paragraph.
5.- Make the footer on first page larger.
6.- Include Logos from all partners??? (not sure if this required)
7.- Maybe too much text in the second sheet. The technical approach is fine (it requires from explanation) but the key challenges could be shortened and highlighted

**Comment by Interoute123** [comment]
Fixes as per Jose's remarks. V2 on Zettabox

**Comment by qshacker** [comment]
Some comments to the flyer

1. The Company name: QSC AG - all in capital letters with a space in-between
2. For the description of the areas we are targetting .....perhaps we could change the "smart grid in the energy sector" into
    --- "smart management solutions for the energy sector"
