### ISSUE TITLE
Discuss realization alternatives for integrating shared public reference data into a cloud deployment (single, clustered, multi-cloud)

### ISSUE THREAD

**Issue by mathiasslawik** [cyclone-project/cyclone-tracking#160]
This pertains to user stories 11 and 16 as well as requirement 11, 12, and 16. There should be a discussion on what alternatives there are to meet this requirement and which tasks need to be done by the partners in order to implement those user stories.

**Comment by cblanchet** [comment]
We can manage it at the user level (bioinfo admin) with the Biomaj toolkit, or with infrastructure mechanisms like automated directory replication, or bloc storage replication (that can be read-only)
