### ISSUE TITLE
Discuss integration of block- and filesystem storage into use cases deployment

### ISSUE THREAD

**Issue by mathiasslawik** [cyclone-project/cyclone-tracking#161]
The storage should be able to be shared, it should allow federated access, and it could be replicated or accessed through multple clouds. We first need to make the requirements more clear and then need to identify if we just integrate common APIs and services or if we need to create new capabilities within Slipstream, our infrastructure (StratusLab, OpenStack), and the security components.

**Comment by cblanchet** [comment]
This requirement implies new capabilities within Slipstream and potentially the network and security components to combine the related requirements about the isolation of the VMs and the access from the authorized user(s).
