### ISSUE TITLE
Discuss concepts of flexible VM sharing

### ISSUE THREAD

**Issue by mathiasslawik** [cyclone-project/cyclone-tracking#162]
Certain user stories require flexible sharing of a common VM. There should first be a discussion what we need specifically and then we should identify what functionality needs to be added to the CYCLONE components.

**Comment by cblanchet** [comment]
An user need to be able to be able to share dynamically (once the VM is running) the access to its VMs for collaboration purpose or debugging/hotline intervention. Currently we are doing it by adding the public SSH key to the related file (authorized_key) or by giving the complete URL (with the hash included) for the web access. The first is not easy to do by a non-linux user, and can be required even if the user VM is providing a web portal. And the second one has a limited level of security.

**Comment by lodygens** [comment]
One easy solution would be to insert debugger/hotline public key(s) in the contextualization procedure at VM creation time. So that debugger/hotline member could easily connect to the running VM through ssh.

**Comment by mathiasslawik** [comment]
I think the latest concept is based on a parameterization of SlipStream deployments.

We add a deployment parameter, for example containing a list of SSH keys or user identities, which is used to configure the authorization on the machine. Then, the cloud portal (or an addition to it) can provide an interface to changing these parameters. If the Bioinformatics user wants to change the list of authorized users, they edit these parameters through the cloud portal and the portal invokes a "null scaling" in SlipStream which causes the configuration of the machine to be updated.

**Comment by ilke-zilci** [comment]
We implemented this with the pam user whitelist
