### ISSUE TITLE
Detail VPN connectivity requirements for the use cases

### ISSUE THREAD

**Issue by mathiasslawik** [cyclone-project/cyclone-tracking#164]
Either detail the VPN connectivity requirements for the use cases or remove it from the spreadsheet and defer this task to year 2 milestone.

**Comment by cblanchet** [comment]
The UC1 an UC2 require an isolated network for the user VMs. They also require a secured connection between the user computer and the VMs for the data transfers, the SSH and web portal access. Should it be treated with a VPN or an other technology, I let you tell me.

**Comment by cblanchet** [comment]
The requirements was detailed in collaboration with WP5 and lead to the WP5 VPN prototype.
