### ISSUE TITLE
Provide a first version of M321

### ISSUE THREAD

**Issue by cblanchet** [cyclone-project/cyclone-tracking#169]

**Comment by cblanchet** [comment]
A first document was uploaded in OneDrive (Cyclone / WP3 / M321)

**Comment by loomis** [comment]
In addition to the use cases from SixSq described in the draft, there is another bioinformatics application that was presented at UCC 2015 that uses application-specific benchmarking to decide where to place VMs.  From our perspective, this would be an interesting example to add application monitoring in the service broker database and use that for placement.  They currently have hacked together scripts to do essentially what SlipStream does but have to improve and then maintain those scripts.  They would likely benefit from SlipStream for that part and possibly the integration with an "App Store" either in a separate portal or through SlipStream.  The person presenting was Thomas Connor and the title of the presentation was "Automated cloud brokerage based upon continuous real-time benchmarking."  I'll send a copy of the paper on the mailing list.  The paper should not be posted publicly.
