### ISSUE TITLE
Define networking solution for VM connectivity with cyclone requirements

### ISSUE THREAD

**Issue by isartcanyameres** [cyclone-project/cyclone-tracking#171]
Define a networking solution bringing connectivity to VMs in different DCs while providing the isolation required for Cyclone use cases.

Once the proposed solution is more clear to us, we will present it to the consortium for comments and improvements.

**Comment by isartcanyameres** [comment]
Three solutions types were identified:

- VPN in software. VPNs and Firewalls are configured in VMs deployed by SlipStream. Works as an IP overlay. No QoS supported. VPNs and Firewalling may offer a management API to be used remotely by NMSs.
- VPNs in hardware. VPNs are configured in the ToR. Requires OpenStack and access to the ToR. Requires an OpenStack neutron implementation that can deal with dynamic configuration of the ToR to dynamically configure VPNs there. There is no current neutron implementation doing this.
- Intra-DC QoS. Requires OpenStack and access to the DC networking infrastructure. Requires an OpenStack neutron implementation that can deal with dynamic configuration of QoS in the whole network infrastructure between the VMs involved. There is no current neutron implementation doing this.

**Comment by isartcanyameres** [comment]
Currently trying to refine first solution (VPN in software) and defining the complete tentative workflow for deployment and operation of the solution.

**Comment by mohamedzayedlal** [comment]
Hi Isart how r u ? I see that your are working on the VPN solution. Could you please tell me which VPN your are using ... If you could i could try to do some tests manually on our openstack cloud ... Thank you

**Comment by lodygens** [comment]
LAL starts testing VPN deployment over 2 clouds OpenStack, using [openvpn.net](https://openvpn.net/).
We are using two OpenStack deployment:
 - keystone.lal.in2p3.fr (OpenStack LAL public cloud)
 - devstack.lal.in2p3.fr (DevStack LAL private development cloud)

**Comment by isartcanyameres** [comment]
The solution has been defined to use OpenVPN-based SlipStream deployment, to generalize VM connectivity management in every cloud, every architecture and OS.

We are currently testing the deployment with SlipStream on available clouds.

**Comment by Josyab** [comment]
@isartcanyameres what is the staut sof this issue? in case it can be closed, please do it. Otherwise, move it to Milestone 12 please.

**Comment by isartcanyameres** [comment]
The solution is the VPN service already implemented.
