### ISSUE TITLE
Manually deploy networking solution to cyclone testbeds (validation)

### ISSUE THREAD

**Issue by isartcanyameres** [cyclone-project/cyclone-tracking#173]
The goal of this deployment is to validate the solution is functional in current testbeds.
It should be checked that the solution provides connectivity while creating desired isolation.

**Comment by mohamedzayedlal** [comment]
Hello guys,
how can manually deploy the network solution at LAL ? Is there any package available to download ??

**Comment by isartcanyameres** [comment]
Hello,
This task shall wait for #171 to finish before it can be started. So, nothing to do right now.

It is expected that this task would consist of launching several CLI commands in both hosts and client VMs to configure the network as defined in #171.

**Comment by isartcanyameres** [comment]
CLI commands have been identified and manually tested @ OpenStack, @ locally, @ internal deployment.

Now integrating with SlipStream
