### ISSUE TITLE
Lead the discussion on the scope and preparation CYCLONE tools tutorials

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-tracking#18]
As a cyclone consortium member I want to participate in the discussion of the tutorials scope, target people, etc with a major focus on the the APIs, interfaces which will enable to interact with other tools.

**Comment by eduesc** [comment]
As greed in the Planning meeting we have to discuss:
- Which tools
- Scope
- Dates
- Target audience
- Format of tutorial

**Comment by eduesc** [comment]
Already discussed and agreed.
