### ISSUE TITLE
Ask to PO about KPIs' commitment

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-tracking#19]
As a member of CYCLONE i want to know if the KPIs we wrote in the DoA document are a strong commitment to be achieved by the consortium or just some indicative values.

**Comment by Interoute123** [comment]
We were requested to add KPIs when preparing DoA. It was a cooperative work, and we agreed on their formulation and values.
KPIs are indicators we think the project could achieve at minimum
Are there problems with some KPIs? Which ones? Let’s discuss at the meeting
But let's try to find a way to approach and solve issues from a technical point of view. We've 3 years to fulfill KPIs
We prefer not to ask the PO on KPI interpretation, implicitly we could raise a warning on a potential problem with us just 5 months after the contract start.
