### ISSUE TITLE
Discuss user mapping eduGAIN user to linux system users on IFB VMs

### ISSUE THREAD

**Issue by ilke-zilci** [cyclone-project/cyclone-tracking#190]
PAM module or another script can create a new user for the eduGAIN user, allow as root or work with an existing ordinary user
Whitelist checks if edugain user allowed as linux user in the ssh login request

**Comment by Sturgelose** [comment]
This has implemented in commit https://github.com/cyclone-project/cyclone-python-pam/commit/2f3ee179027d9d9a3d60d966918973c77f5523c7

The idea is that each user will have an .edugain file in their home folder, where they indicate which edugain users can login as the specified user. More information regarding this implementation has been added in the readme.
