### ISSUE TITLE
Discuss how IFB appliance owner manages the whitelist and user rights in the SSH connection using federated identity context

### ISSUE THREAD

**Issue by ilke-zilci** [cyclone-project/cyclone-tracking#191]
Initial ideas: 
Owner can add auto created eduGAIN users to sudoer or these remain just regular user
File editing to add user to whitelist might not be the best way, we could parameterize users to be added to the whilelist in the deployment phase.

**Comment by Sturgelose** [comment]
As we discussed, the users should be created during deployment and then add the .edugain to its folder in order to select which users are allowed to login as the specified user.

In deployment fase, this file just should be created to allow the first users to login

**Comment by ilke-zilci** [comment]
IFB manually deployed a VM with the PAM module and it meets their requirements. We will add a recipe on nuvla to show integration, user emails can be parameterized, appliance owner can still change the files after the deployment is done.

**Comment by ilke-zilci** [comment]
The home folder of the user and the simple list fulfills the IFB requirements. For more on this, see CYCLONE-pam readme in the repo
