### ISSUE TITLE
Discuss security requirements of the energy use case

### ISSUE THREAD

**Issue by ilke-zilci** [cyclone-project/cyclone-tracking#195]
We should find out concrete requirements and implementation tasks till the end of the week of 22nd.

**Comment by ilke-zilci** [comment]
We have to clarify use case description documents: how the energy use cases relate to federated login, federated authorization, end to end security.

**Comment by ilke-zilci** [comment]
We are agreeing on an appointment at the week of 4th April

**Comment by lodygens** [comment]
Dear Ilke april, 4th was not on the doodle proposision (http://doodle.com/poll/b2hh4btewxc4mxm8)
:)

**Comment by ilke-zilci** [comment]
We had a productive discussion on 20.05 , see minutes on onedrive.
