### ISSUE TITLE
IFB use case: Requirement #9 implications in terms of networking.

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-tracking#198]
Identify the scope of requirement #9.

The outcome should be:
- A decision on whether it makes sense to implement this requirement in terms of networking.
- I2CAT to create an issue to track the implementation.

**Comment by Josyab** [comment]
The meeting has been scheduled by Thursday 25th.

**Comment by Josyab** [comment]
@isartcanyameres: I have this one assigned. Fromt he discussions we had with Mohamed and Christophe, can we close this one? Do we count already with the required information?

**Comment by cblanchet** [comment]
Done
