### ISSUE TITLE
IFB use case: Requirement #26, #27 and #28 implications in terms of networking

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-tracking#199]
Identify the scope of requirements 26, 27 and 28.

The outcome should be:

A decision on whether it makes sense to implement this requirements in terms of networking.
I2CAT to create an issue to track the implementation.

**Comment by Josyab** [comment]
@isartcanyameres: I have this one assigned. Fromt he discussions we had with Mohamed and Christophe, can we close this one? Do we count already with the required information?

**Comment by isartcanyameres** [comment]
Ping TUB and IFB

**Comment by cblanchet** [comment]
#26 requires a collaboration with GEANT
#27 to be able to select the clouds with "cold" storage
#28 that slipstream manages bloc storage and the selected cloud provides access to local disks of the hypervisors
