### ISSUE TITLE
partner descriptions

### ISSUE THREAD

**Issue by loomis** [cyclone-project/cyclone-tracking#2]
As a CYCLONE participant, I can find a short, plain-text description of each partner (including its activities in CYCLONE) in the project's document repository.

**Comment by cblanchet** [comment]
Waiting the invitation to join the zettabox to be able to upload the requested document.

**Comment by loomis** [comment]
- [ ] Interoute
- [ ] SixSq
- [ ] QSC
- [ ] TUB
- [ ] i2CAT
- [ ] UvA
- [ ] CNRS-LAL
- [ ] CNRS-IFB

**Comment by Josyab** [comment]
i2CAT info file has been provided.

**Comment by lodygens** [comment]
CNRS LAL uploaded to Zettabox

**Comment by cblanchet** [comment]
Done for CNRS IFB

**Comment by Josyab** [comment]
All are available in ZettaBox in General/Partner
