### ISSUE TITLE
Check if we opted out of the open publications program

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-tracking#21]
As CYCLONE member i want to know with regards reporting if we opted out of the open publications program

**Comment by eduesc** [comment]
In Section 5 (Call specific questions), Open Research Data Pilot in Horizon 2020 we selected (YES) in:
- We wish to opt out of the Pilot on Open Research Data in Horizon 2020
so we do not need a data management plan.
However we declared that we will try to have open data publications if possible and that we allocated part of the budget to cover the expenses of open data publications.
