### ISSUE TITLE
Investigate on available video methods

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-tracking#22]
As a CYCLONE member i need to know the video sharing tool that we will be using for the Demo meetings.

**Comment by cblanchet** [comment]
The French NREN provides an online videoconference system based on Jitsi. 
https://rendez-vous.renater.fr

**Comment by eduesc** [comment]
https://rendez-vous.renater.fr worked fine in the Sprint 0 DEMO meeting and will be the video conferencing system used for the following DEMO meetings.
