### ISSUE TITLE
Publish the UCs description on the project web site

### ISSUE THREAD

**Issue by cblanchet** [cyclone-project/cyclone-tracking#233]

**Comment by ilke-zilci** [comment]
Django Use cases app integration with CYCLONE fed pro almost ready. Could you elaborate on this please, @bryan-brancotte ?

**Comment by bryan-brancotte** [comment]
The Django Use cases app is almost ready. The integration of the CYCLONE fed pro is also almost ready.
We will come back at you soon when the app is ready.

**Comment by bryan-brancotte** [comment]
Website is up and running at [https://cyclone.france-bioinformatique.fr/usecases/](url)
