### ISSUE TITLE
Connect IFB's portal with nuv.la portal through its public API

### ISSUE THREAD

**Issue by cblanchet** [cyclone-project/cyclone-tracking#243]
To make the IFB's portal able to launch virtual infrastructures on the CYCLONE testbed

**Comment by cblanchet** [comment]
First tests have been done. 
Got no answer from http://ssapi.sixsq.com/#authentication with a valid account

**Comment by bryan-brancotte** [comment]
With more details : I have tried the use the api, but when i try the authentication (http://ssapi.sixsq.com/#authentication) i don't have any answers. I have tried with my nuv.la account, and on a slipstream server which was installed at the IFB.
Note that my account nuv.la is not working anymore.

**Comment by rbf** [comment]
@bryan-brancotte: Don't hesitate to directly contact me or @loomis (here or on Slack) when you face those issues.

**Comment by bryan-brancotte** [comment]
SixSq have shown me how to sign in and do basic operation using urls and curl.
Next step requires a python api client. We have to decide who will develop it ? (SixSq or IFB)
