### ISSUE TITLE
Organize logistics for the Rehearsal in Brussels on September the 18th

### ISSUE THREAD

**Issue by Interoute123** [cyclone-project/cyclone-tracking#255]
Any suggestion on possible location is more than welcome

**Comment by eduesc** [comment]
We might have the possibility of booking a meeting room free of charge at some offices of the Catalan government at Rue de la Loi, 227, but I should ask if it's open on Sunday.

**Comment by eduesc** [comment]
Ok, just checked. Sundays it's closed, so we need more suggestions.

**Comment by Josyab** [comment]
For other reviews the team was hosted in ibis Hotel Brussels Centre Ste Catherine

http://www.booking.com/hotel/be/ibisstcatherine.en-gb.html?label=gen173nr-1FCAEoggJCAlhYSDNiBW5vcmVmaEaIAQGYAS64AQbIAQzYAQHoAQH4AQuoAgM;sid=e3268a93f5dd5530e3c3bfb7dd443914;dcid=4;checkin=2016-09-17;checkout=2016-09-19;ucfs=1;highlighted_blocks=2015113_400206_0_2;room1=A,A;hpos=1;dest_type=city;dest_id=-1955538;srfid=b0e59269b368cf75a3df8ea0bd8efbc9261a2190X1;highlight_room=

Which is OK, close to the metro and counts with rooms to carry out the rehearsal. This could be an option (the rooms are quite reasonable now)

**Comment by Interoute123** [comment]
We are about to book the facility Jose' proposed.

**Comment by Interoute123** [comment]
The facility has been booked.
