### ISSUE TITLE
Provide a web site to manage use cases

### ISSUE THREAD

**Issue by cblanchet** [cyclone-project/cyclone-tracking#265]
Main goals:
- display the public information of the use cases: description, requirements 
- help use case leaders to describe their use case

**Comment by cblanchet** [comment]
A first release is available. The federation provider is integrated in the portal. 
https://cyclone.france-bioinformatique.fr/usecases

**Comment by bryan-brancotte** [comment]
Note that the visitor account is disabled as the federated authentication based on edugain is now available.
