### ISSUE TITLE
first draft of D2.1

### ISSUE THREAD

**Issue by loomis** [cyclone-project/cyclone-tracking#28]
As a CYCLONE participant, I can find and review the first draft of D2.1: CYCLONE Branding Strategy.

**Comment by lodygens** [comment]
Where is the document? Thanks

**Comment by loomis** [comment]
The first draft of D2.1 (basically an outline with some information filled in) is available in ZettaBox.  The folder is Documents/Draft/D2.1/CYCLONE-D2.1-M03-V0.1.docx in the project's shared folder.

To manage the feedback on the document:
  - Provide general comments on the document (content, scope, organization, etc.) as comments within this issue.
  - For detailed editorial changes, create a copy of the document in the shared folder, renamed by appending your initials, and with change tracking on.

Please review and provide feedback before Tuesday, 17 February 2015.

**Comment by lodygens** [comment]
can we have access to the project shared folder ?
:)


Oleg Lodygensky
Laboratoire de l'Accelerateur Lineaire
Universite Paris Sud 11
Bat 200
91898 Orsay Cedex
France

T�l +33 (0)1 64 46 82 75
Mobile +33 (0)6 52 85 71 21
Fax +33 (0)1 69 07 94 04
email : oleg.lodygensky@lal.in2p3.fr
Web : http://www.xtremweb-hep.org



Le 12 f�vr. 2015 � 14:28, Charles (Cal) Loomis <notifications@github.com> a �crit :

**Comment by loomis** [comment]
First draft is finished. No comments.  Will open issue for final draft.
