### ISSUE TITLE
Provide VPN documentation including "logs" info

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-tracking#289]
I2CAT will provide VPN documentation (logs and everything) that could be used as a kind of service monitoring.

**Comment by isartcanyameres** [comment]
Documentation is here:
https://onedrive.live.com/redir?resid=2C3033FE409659BD!1216&authkey=!AGTnUbzKt2RHFuQ&ithint=file%2cpdf

It is not yet clear how to proceed with logs, so logging is not yet implemented
