### ISSUE TITLE
Consider submitting paper to Cloud Forward 2016 

### ISSUE THREAD

**Issue by ydemchen** [cyclone-project/cyclone-tracking#295]
Consider submitting paper to Cloud Forward 2016 if deadline is extended till 24 May 2016.
Investigate possibility to submit joint paper from CYCLONE, GEANT4 and possibly SWITCH.

**Comment by Josyab** [comment]
Deadline is over, so unless you have some fresh news we will miss this one.

**Comment by ydemchen** [comment]
Issue expired, no deadline extension granted.
