### ISSUE TITLE
Update Calendar of events

### ISSUE THREAD

**Issue by ydemchen** [cyclone-project/cyclone-tracking#298]
Update calendar of events for CYCLONE to participate in 2016

**Comment by lodygens** [comment]
Hi Yuri,
is this calendar online?
Thanks

**Comment by ydemchen** [comment]
No. I wa actually referring to Excel file on GD
cycloneDCP related events 2016-2017 - All.xlsx

I don't know if we need online calendar.

Yuri

**Comment by ydemchen** [comment]
Next update of Events calendar to plan in June for autumn period
