### ISSUE TITLE
partner URLs

### ISSUE THREAD

**Issue by loomis** [cyclone-project/cyclone-tracking#3]
As a CYCLONE participant, I can find the list of preferred URLs for each partner in the project's standard document repository.  The URLs point to a location that describes the partner and partner's activities.

**Comment by ydemchen** [comment]
System and Network Engineering Group of the University of Amsterdam
https://ivi.fnwi.uva.nl/sne/

**Comment by lodygens** [comment]
Laboratoire de l'Accélérateur Linéaire : http://www.lal.in2p3.fr

**Comment by Josyab** [comment]
I2CAT Foundation: www.i2cat.net/en

**Comment by ilke-zilci** [comment]
Technische Universität Berlin, Service-centric Networking: http://www.snet.tu-berlin.de

**Comment by cblanchet** [comment]
CNRS - National Centre for Scientific Research : www.cnrs.fr
represented by
- French Institute of Bioinformatics : www.france-bioinformatique.fr
- Laboratoire de l'Accélérateur Linéaire : www.lal.in2p3.fr

**Comment by loomis** [comment]
Tracked in #2.  Please provide information in the template in ZettaBox: `General/Partner/*.md`.
