### ISSUE TITLE
D2.1: incorporate comments and produce final draft

### ISSUE THREAD

**Issue by loomis** [cyclone-project/cyclone-tracking#32]
Incorporate any comments for the first draft and then produce the final draft for review.

**Comment by loomis** [comment]
The first complete draft and proposed final draft is available in ZettaBox (`CYCLONE-D2.1-M03-V0.2.docx`).  General comments about the draft can be added to this ticket.  Specific changes can be added directly to the draft (or a copy of it) with change tracking on.

**Comment by eduesc** [comment]
I will review it
