### ISSUE TITLE
Integrate all network services in a single component

### ISSUE THREAD

**Issue by isartcanyameres** [cyclone-project/cyclone-tracking#320]
As an application developer, I want to have a single component able to launch all network services (VPN, FW and LB).

The server component should be able to run the VPN server and the LB server.
Clients should be able to run VPN clients, FW and LB clients.

Ideally, as an application developer I want to select which services to be deployed (between VPN, FW and LB).

**Comment by Josyab** [comment]
The three services have been integrated in a single application and can be found in https://nuv.la/module/cyclone/wp5_net_services_applications/integrated/IntegratedDEMO
The documentation is also available at:
https://1drv.ms/b/s!Ar1ZlkD-MzAsiiak0oks_1vGRflf

Some minor adjustments may be done to speed up the deployment, but the application is working.
