### ISSUE TITLE
Stratuslab Tutorial

### ISSUE THREAD

**Issue by eduesc** [cyclone-project/cyclone-tracking#33]
As an expert on Stratuslab I will prepare the documentation needed for the tutorial and will be in charge of its preparation.

**Comment by lodygens** [comment]
We will propose our Stratuslab tutorial: https://indico.in2p3.fr/event/9852 in the context of the CYCLONE project.

**Comment by lodygens** [comment]
Slides are in Stratuslab documentation/tutorial repository.
To be translated in english ;)

**Comment by lodygens** [comment]
Slides rewritten in english using Cyclone template.
I have pushed them in Zettabox/H2020.Cyclone/WP7-Testbed/
Any comment welcome.
By the way, I am not sure if we already schedulled anything ?

Still missing appliance tutorial...

**Comment by lodygens** [comment]
Oups! Sorry; I see #55 was about schedulling stratuslab tutorial... 
:D
I'll open a doodle :)

**Comment by lodygens** [comment]
Three tutorials available in Zettabox/H2020.Cyclone/WP7-Testbed :
- cloud install
- client install
- appliance management

**Comment by lodygens** [comment]
Stratuslab tutorial doodle:
http://doodle.com/hd25vie7vuagdriu

**Comment by lodygens** [comment]
The Stratuslab tutorial will take place on Avril 16th, at 10:00
