### ISSUE TITLE
OpenNaaS Tutorial

### ISSUE THREAD

**Issue by eduesc** [cyclone-project/cyclone-tracking#34]
As an expert on OpenNaaS I will prepare the documentation needed for the tutorial and will be in charge of its preparation.

**Comment by Josyab** [comment]
I will take care of this. I believe the sooner we can show this the better.

**Comment by Josyab** [comment]
The same approach that is being discussed for TRESOR (issue #44 ) is being proposed also for OpenNaaS. Discussions are ongoing.

**Comment by Josyab** [comment]
For OpenNaaS we are thinking on the following structure:

1.- Non-technical webinar on OpenNaaS.
2.- Hands on:

   - 1st exercise ("hello world" level)
   - 2nd exercise (Optional). Something a little bit more complex
   - 3rd exercise (optional). "The challenge": Something more ambitious for
   those who want to go further and squeeze the tutorial.

3.- How to integrate/extend OpenNaaS to be part of the solution ( As
Mathias proposes: "some of the code to know, where to integrate").

**Comment by Josyab** [comment]
We will follwo this in #57
