### ISSUE TITLE
SlipStream Tutorial

### ISSUE THREAD

**Issue by eduesc** [cyclone-project/cyclone-tracking#35]
As an expert on SlipStream I will prepare the documentation needed for the tutorial and will be in charge of its preparation.

**Comment by loomis** [comment]
A previous tutorial can be found here: https://indico.lal.in2p3.fr/event/2633/.  This material needs to be updated and expanded for the CYCLONE tutorial.  I hope to do this tutorial in the next two weeks probably by Adobe Connect or similar system.

**Comment by Josyab** [comment]
Hi all, 

We confirmed with Cal that the Slipstream tutorial will take place next Tuesday 5th of May.

He will be providing the details, requirements and starting hour ASAP.

**Comment by loomis** [comment]
The tutorial will take place 13:30-17:30 (Geneva).  The only things you need for the tutorial are:

1) Laptop/desktop with recent, modern browser

2) Account on the StratusLab infrastructure at LAL (https://cloud.lal.stratuslab.eu/register/)

3) Account on the Exoscale cloud

4) Access to your email account for email address verification

Before the tutorial: 

1) Please read through the sections of the “Advanced Tutorial” on http://ssdocs.sixsq.com, from the “Advanced Tutorial” introduction through the “Remote Machine Access”.  You’ll not need the parts explaining the cloud, but knowing the SlipStream terminology will be helpful. 

2) Create your cloud accounts.  For exoscale, send me an email and I’ll send you back a code that gives you a 20€ credit.  (This is individual for each person.)

3) Setup your machine for SSH access as described in the tutorial documentation. 

Cheers.

Cal

**Comment by loomis** [comment]
Done.
