### ISSUE TITLE
Prepare materials for TRESOR Tutorial (Proxy, Broker, TCTP, XACML Authorization, ...)

### ISSUE THREAD

**Issue by eduesc** [cyclone-project/cyclone-tracking#36]
As an expert on the TRESOR proxy I will prepare the documentation needed for the tutorial and will be in charge of its preparation.

**Comment by mathiasslawik** [comment]
Some ideas for tutorial structure:

* TRESOR Ecosystem
 * Overview
 * Fig-based demo deployment
* TRESOR Proxy
 * Overview
 * How to install and run
 * Functionalities in the Proxy
* TCTP
 * Overview
 * Demo: Enable secure End-to-end encryption
* TRESOR Broker: SDL
 * Overview
 * Syntax of Service Descriptions
* TRESOR Broker
 * Vocabulary
 * API overview
 * Demo: Describing a service
* Further functionality
 * Single Sign-On Authentication
 * Authorization through XACML
 * Creating access policies through TRESOR PAP
 * Unified Logging

**Comment by mathiasslawik** [comment]
There are some prerequisites for doing this tutorial:

- [ ] [Fix SDL-NG documentation](https://github.com/TU-Berlin-SNET/sdl-ng/issues/12)
- [ ] [Include an open source IDM in the TRESOR Ecosystem docker build](https://github.com/TU-Berlin-SNET/tresor-ecosystem/issues/1)

**Comment by mathiasslawik** [comment]
Hi,

the slides are available in our share under Meetings\201504XX-TRESOR-Tutorial.

We'll circulate installation instructions in the next days.

Best regards,
Mathias

**Comment by ilke-zilci** [comment]
The prerequisits are not relevant any more. The tutorial is ready as it is.

**Comment by qshacker** [comment]
Thanks for the slides and further Information to the tutorials, unfortunately we can't access the visio files quite well. Is it possible for you to export them to for example PDFs so that they are also accessible on iPads and so on.
Thanks in advance
Best regards
Doris
