### ISSUE TITLE
Conduct Tutorial on UvA components

### ISSUE THREAD

**Issue by eduesc** [cyclone-project/cyclone-tracking#39]
As an expert on SAML/XACML I will prepare the documentation needed for the tutorial and will be in charge of its preparation.

**Comment by mathiasslawik** [comment]
Hi Yuri,

I'd like to hear about the libraries you've developed, GAAA-TK and DACl. Do you have some existing documentation - I've looked at the repos and did not find much README or code comments.

I don't think we should concentrate on SAML or XACML, as those are widely used industry standards. But that is just my opinion. What do you think?

Best regards,
Mathias

**Comment by ydemchen** [comment]
Mathias, 
what do you mean "we *should not concentrate* on SAML or XACML, as those are widely used industry standards"?
We need to use standards for our purposes and to be compatible with existing security services.

Yuri

**Comment by mathiasslawik** [comment]
Yuri,

I meant *for the tutorial*. As we should all know SAML and XACML, we should concentrate on tutoring the implemented software.

Do you have more information about GAAA-TK and DACl? I did not find very much information.

Best regards,
Mathias

**Comment by ydemchen** [comment]
Mathias,

I will collect all available docs and provide links or put on our shared 
media.

About tutorials, this is not about standards but how we use them; there 
are some tricks and mechanisms that we use to manage security context.

Yuri

**Comment by Josyab** [comment]
@ydemchen : Have you already shared the proposed documents?

If so please specify the folder and close the ticket.
If not yet, please share them.

**Comment by mathiasslawik** [comment]
We have just agreed on the following items in the Sprint 6 demo meeting:
-> Have a UvA tutorial after the meeting in Berlin, incorporating discussion results about security
-> UvA will ask the mailing list who wants to attend. Possibly UvA, TUB, i2cat, and QSC
-> UvA will send around a doodle quering for possible dates
-> UvA will distribute some comprehensive slides before the meeting

I think the tutorial should be on SNE-XACML, DACI, and Trust Bootstrapping

**Comment by Josyab** [comment]
@ydemchen and @turkmenf : If the tutorial on SNE-XACML, DACI, and Trust Bootstrapping is still going to take place, move this issue to "defered" milestone. 

If it is no longer needed, please close the issue.

Thanks!
Jose

**Comment by turkmenf** [comment]
After F2F meeting, we have now an understanding of the components involved in DACI. SNE-XACML is a XACML engine that is used by DACI. I also sent a document to relevant partners (TUB) that explains these components in detail. 

In overall, this issue is not relevant any more and can be closed.
