### ISSUE TITLE
Bioinformatics use case analysis

### ISSUE THREAD

**Issue by eduesc** [cyclone-project/cyclone-tracking#42]
We have to start the discussion around this case and its requirements.
The outcome of this issue will be a document with the description of the use case and a list of requirements.

**Comment by Josyab** [comment]
Two/three pages document is required to start discussing and polishing the showcase, retrieve software tools' requirements,  WP7 infrastucture needs, etc.

**Comment by cblanchet** [comment]
Upload in zettabox a first version of the bioinformatics use cases analysis

**Comment by eduesc** [comment]
First version uploaded by Christophe. Comments and further analysis in ticket #54
