### ISSUE TITLE
Paper on service matchmaking 

### ISSUE THREAD

**Issue by ilke-zilci** [cyclone-project/cyclone-tracking#47]
As a participant of CYCLONE, I want to publish the results of the research on service matchmaking in a preferably European conference.

**Comment by lodygens** [comment]
I would be happy to participate. Where are you with all that? Is it still in to do list or do you have started anything?

**Comment by ilke-zilci** [comment]
I have submitted a paper with my master's thesis topic which was more focused on cloud service marketplaces and waiting for notification of acceptance. It would be great to write a joint paper focused on the inter-cloud context.

**Comment by ilke-zilci** [comment]
The paper was accepted, so now I'm working on the camera-ready version.

**Comment by ilke-zilci** [comment]
Camera-ready submitted.
