### ISSUE TITLE
Energy Use case analysis - 2 round

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-tracking#53]
Once issue #43 is achieved, organize a conference call with the rest of the partners to discuss (brain storming) on additional requirements (functional and non-functional) that the showcase may include. 

Some foreseent activities:

•	Liaise with developers and analyze their use cases
•	Provide a set of requirements associated with these use cases
•	Select and schedule work cases in collaboration with the project’s agile development team
•	Work with developers to adapt the selected applications to a dynamic, multi-cloud deployment.

The outcome of this issue is an improvement of the first use case description

**Comment by cblanchet** [comment]
That point has been addressed for the MS11
