### ISSUE TITLE
Set a date for Statuslab tutorial

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-tracking#55]
I want to know when the StratusLab tutorial will be provided.

**Comment by Josyab** [comment]
Agree on a date to deliver the Stratuslab tutorial.

Note: All the tutorials should be  delivered by the end of April '15

**Comment by lodygens** [comment]
why is there this new ticket?
there already is ticket #33 
this is very confusing; please close this ticket, we will continue with ticket #33

**Comment by Josyab** [comment]
Sorry for the confusion Oleg. My bad. 
I just made a short re-wording, but if you still see this one not necesary, it´s fine if you want to close it.

**Comment by lodygens** [comment]
:)
