### ISSUE TITLE
OpenNaaS tutorial

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-tracking#57]
Agree on a date to deliver the OpenNaaS tutorial.

Note: All the tutorials should be  delivered by the end of April '15

**Comment by Josyab** [comment]
For OpenNaaS we are thinking on the following structure:

1.- Non-technical webinar on OpenNaaS.
2.- Hands on:

1st exercise ("hello world" level)
2nd exercise (Optional). Something a little bit more complex
3rd exercise (optional). "The challenge": Something more ambitious for those who want to go further and squeeze the tutorial.
3.- How to integrate/extend OpenNaaS to be part of the solution ( As
Mathias proposes: "some of the code to know, where to integrate").

**Comment by Josyab** [comment]
The date is still to be decided. A doodle will be proposed this week

**Comment by Josyab** [comment]
Doodle for OpenNaaS tutorial. It will be closed on Friday 17th.

http://doodle.com/x8u7raxdkn6y3stf

**Comment by lodygens** [comment]
I have created a rendez vous for OpenNaaS tutorial:
https://rendez-vous.renater.fr/cycloneopennaastutorial

**Comment by Josyab** [comment]
OpenNaaS tutorial will be the 4th of May at 15:00 CEST.

The link to attend to the training is:
https://rendez-vous.renater.fr/cycloneopennaastutorial

Previous required information and installations will be detailed in advance of the tutorial.

**Comment by Josyab** [comment]
Dear all,

This is a kindly reminder for the OpenNaaS tutorial taking place the 4th of May (next Monday).

The tutorial will cover following topics:
1.- Introduction to OpenNaaS
                Key concepts
2.- OpenNaaS for developers
                Technological framework
                Interacting paradigms
3.- Hands on - lab session
                Example code review
                Extending the example on your own
4,. OpenNaaS in the real world
               Managing an OpenDaylight controller
5.- Q&A


Please do not forget to get through following steps to prepare your environment in order to follow the tutorial:

1.- Install Oracle VirtualBox 4.3.x (in case you don't have it already)
                   You can get it from your system's software manager
                    Or from the product page: https://www.virtualbox.org/wiki/Downloads

2.- Download the VM image we have prepared with the dev environment (4,8GB). It make take time depending on your internet connection (took 20 minutes in my case):
                   VM image: https://drive.google.com/a/i2cat.net/uc?id=0BwjF-XINqUEATXV2N0lUQjFtMFU&export=download

3.- Import the VM in VirtualBox:
            File > Import Virtual Appliance > Insert path to downloaded VM image > Next > Import
           It may take a few minutes (took 10 minutes in my case)
           The VM requires 2GB RAM, and 12GB disk space to run. 

4.- Launch the VM to ensure it loads successfully. (nothing else is required so you can just shut it down)

Please notice that VM RAM requirements are huge, so a machine with 4GB RAM or more may be required to follow the tutorial with the VC system and the VM simultaneously.
