### ISSUE TITLE
Create Milestone ToC for M701

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-tracking#58]
Create Milestone ToC for M701 due by M4.: Architectural and technical view of solution: Verification and coordination with respect to all the other software components

Circulate the ToC to receive feedback.

Create the final M701 ToC and assign sections to involved partners

**Comment by Josyab** [comment]
Any progresses on this?

**Comment by eduesc** [comment]
First version of ToC uploaded by Doris and awaiting for comments.

**Comment by Josyab** [comment]
Hi,

We alaready provided comments to the ToC version. 
Since then, sections' assignments, and a calendar to provide the inputs should be agree. Could Doris pleased take care of this?

**Comment by mathiasslawik** [comment]
Done.
