### ISSUE TITLE
Improve the project website design

### ISSUE THREAD

**Issue by ilke-zilci** [cyclone-project/cyclone-tracking#59]
The "banner" size should be bigger and always the same size on every page.

**Comment by Josyab** [comment]
Next actions to be done:

- We need a favicon with the logo.
- The "banner" size should be bigger and always the same size in the different pages.
- We need a more attractive design, can Interoute design agency do that?
- We should add the logos of CYCLONE software components
- We should add the logos in the press page for download

**Comment by ilke-zilci** [comment]
Actually the favicon and the logos for download are there and the banner size is same on each page. I think the point with the "more attractive design" should be discussed in another ticket. Currently open issues are:
- [ ] home page with three logos instead of three text columnss, and then click on the logos to see more information.
- [ ] add the logos of CYCLONE software components. Find a way to make it look ok for all components, since not all software components have logos.
- [ ] The "banner" size should be bigger.

**Comment by ilke-zilci** [comment]
Changes can be seen on the live site.
