### ISSUE TITLE
Install TRESOR Ecosystem via Docker following the readme

### ISSUE THREAD

**Issue by ilke-zilci** [cyclone-project/cyclone-tracking#60]
As a CYCLONE member who is interested in attending the tutorial, I want to install the TRESOR ecosystem following the steps at : https://github.com/TU-Berlin-SNET/tresor-ecosystem so that I  can report any problems to the TRESOR developers as tickets at https://github.com/TU-Berlin-SNET/tresor-tracking before the tutorial.

**Comment by lodygens** [comment]
I have several warning messages: "can't parse SRV; message too long" as shown below


Step 4 : RUN /bin/bash -c "source /usr/local/rvm/scripts/rvm && bundle install && rake assets:precompile"
 ---> Running in d731f698237a
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching source index from https://rubygems.org/
Fetching git://github.com/bmabey/database_cleaner.git
warning: cannot parse SRV response: Message too long
Fetching git://github.com/mongoid/mongoid.git
warning: cannot parse SRV response: Message too long
Fetching git://github.com/thetron/mongoid-enum.git
warning: cannot parse SRV response: Message too long
Fetching git://github.com/asalme/radix.git
warning: cannot parse SRV response: Message too long
Fetching git://github.com/slim-template/slim.git
warning: cannot parse SRV response: Message too long
Installing rake 10.3.2
Installing i18n 0.6.11
...
Step 4 : RUN /bin/bash -c "source /usr/local/rvm/scripts/rvm && bundle install" &&    chmod +x /root/tresor-proxy/bin/proxy_docker.sh
 ---> Running in 4fa3af5117cb
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/.........
Fetching additional metadata from https://rubygems.org/..
Fetching git://github.com/asalme/radix.git
warning: cannot parse SRV response: Message too long

**Comment by lodygens** [comment]
Then several debconf errors (for different packages) :

Creating config file /etc/php5/mods-available/opcache.ini with new version
php5_invoke: Enable module opcache for cli SAPI
php5_invoke: Enable module opcache for apache2 SAPI
Setting up php5-curl (5.5.9+dfsg-1ubuntu4.7) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype

**Comment by lodygens** [comment]
But these may be warnings only. The installation isnot finished yet; we'll see.
:)

**Comment by lodygens** [comment]
Seems to be stuck at :

esfilter_1      | 2015-04-07T14:26:47.433Z - info: SUCESS node-es-filter-proxy with target http://elasticsearch:9200 now listening on 0.0.0.0:4004

Should I try to "Setup test services in the TRESOR broker"? Or should I wait until the process ends (the process is "docker-compose up"; CPU usage is 0% )  ?

**Comment by ilke-zilci** [comment]
Could you please report the problems on the TU-Berlin SNET TRESOR Tracking Project so that TRESOR developers receive it directly? https://github.com/TU-Berlin-SNET/tresor-tracking

**Comment by ilke-zilci** [comment]
Also please follow the ticket linked above, to see if your question is answered.
https://github.com/TU-Berlin-SNET/tresor-tracking/issues/1

**Comment by lodygens** [comment]
Here I am:

On terminal 1

$> docker-compose up

blabla...

esfilter_1      | 2015-04-07T14:26:47.433Z - info: SUCESS node-es-filter-proxy with target http://elasticsearch:9200 now listening on 0.0.0.0:4004

So, I assume this is running.

On another terminal (terminal 2), I run:
$> docker exec -i -t tresorecosystem_broker_1 /bin/bash -c "source /usr/local/rvm/scripts/rvm && RAILS_ENV=production rake tresor:setup_environment"

rake aborted!
Moped::Errors::ConnectionFailure: Could not connect to a primary node for replica set #<Moped::Cluster:53721300 @seeds=[<Moped::Node resolved_address=nil>]>
/usr/local/rvm/gems/ruby-2.1.5/gems/moped-2.0.0/lib/moped/cluster.rb:248:in `with_primary'
/usr/local/rvm/gems/ruby-2.1.5/gems/moped-2.0.0/lib/moped/read_preference/primary.rb:55:in `block in with_node'
/usr/local/rvm/gems/ruby-2.1.5/gems/moped-2.0.0/lib/moped/read_preference/selectable.rb:65:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/moped-2.0.0/lib/moped/read_preference/selectable.rb:65:in `with_retry'
/usr/local/rvm/gems/ruby-2.1.5/gems/moped-2.0.0/lib/moped/read_preference/selectable.rb:71:in `rescue in with_retry'
/usr/local/rvm/gems/ruby-2.1.5/gems/moped-2.0.0/lib/moped/read_preference/selectable.rb:64:in `with_retry'
/usr/local/rvm/gems/ruby-2.1.5/gems/moped-2.0.0/lib/moped/read_preference/primary.rb:54:in `with_node'
/usr/local/rvm/gems/ruby-2.1.5/gems/moped-2.0.0/lib/moped/database.rb:72:in `command'
/usr/local/rvm/gems/ruby-2.1.5/gems/moped-2.0.0/lib/moped/query.rb:41:in `count'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/mongoid-8cb17e983997/lib/mongoid/persistable/deletable.rb:142:in `delete_all'
/root/tresor-broker/lib/tasks/tresor.rake:38:in `map'
/root/tresor-broker/lib/tasks/tresor.rake:38:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Moped::Errors::ConnectionFailure: Could not connect to a primary node for replica set #<Moped::Cluster:53721300 @seeds=[<Moped::Node resolved_address=nil>]>
/usr/local/rvm/gems/ruby-2.1.5/gems/moped-2.0.0/lib/moped/cluster.rb:248:in `with_primary'
/usr/local/rvm/gems/ruby-2.1.5/gems/moped-2.0.0/lib/moped/read_preference/primary.rb:55:in `block in with_node'
/usr/local/rvm/gems/ruby-2.1.5/gems/moped-2.0.0/lib/moped/read_preference/selectable.rb:65:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/moped-2.0.0/lib/moped/read_preference/selectable.rb:65:in `with_retry'
/usr/local/rvm/gems/ruby-2.1.5/gems/moped-2.0.0/lib/moped/read_preference/primary.rb:54:in `with_node'
/usr/local/rvm/gems/ruby-2.1.5/gems/moped-2.0.0/lib/moped/database.rb:72:in `command'
/usr/local/rvm/gems/ruby-2.1.5/gems/moped-2.0.0/lib/moped/query.rb:41:in `count'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/mongoid-8cb17e983997/lib/mongoid/persistable/deletable.rb:142:in `delete_all'
/root/tresor-broker/lib/tasks/tresor.rake:38:in `map'
/root/tresor-broker/lib/tasks/tresor.rake:38:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => tresor:setup_environment
(See full trace by running task with --trace)


Back on terminal 1, we can see:

esfilter_1      | 2015-04-07T14:26:47.433Z - info: SUCESS node-es-filter-proxy with target http://elasticsearch:9200 now listening on 0.0.0.0:4004


broker_1        | W, [2015-04-08T09:29:34.242795 #27469]  WARN -- : Overwriting existing field _id in class Client.
broker_1        | W, [2015-04-08T09:29:34.252244 #27469]  WARN -- : Overwriting existing field _id in class Provider.
broker_1        | W, [2015-04-08T09:29:34.256553 #27469]  WARN -- : Overwriting existing field _id in class ServiceBooking.
broker_1        | W, [2015-04-08T09:29:34.280163 #27469]  WARN -- : Overwriting existing field _id in class SDL::Base::Type::Service.
broker_1        | W, [2015-04-08T09:29:34.424397 #27469]  WARN -- : Overwriting existing field identifier in class SDL::Base::Type::SpecificLocation.
broker_1        | W, [2015-04-08T09:29:34.426655 #27469]  WARN -- : Overwriting existing field identifier in class SDL::Base::Type::UnspecificLocation.
broker_1        | W, [2015-04-08T09:29:34.527043 #27469]  WARN -- : Overwriting existing field identifier in class SDL::Base::Type::RestInterface.
broker_1        | W, [2015-04-08T09:29:34.528404 #27469]  WARN -- : Overwriting existing field identifier in class SDL::Base::Type::SoapInterface.
broker_1        | W, [2015-04-08T09:29:34.529849 #27469]  WARN -- : Overwriting existing field identifier in class SDL::Base::Type::XmlrpcInterface.
broker_1        | W, [2015-04-08T09:29:34.703291 #27469]  WARN -- : Overwriting existing field identifier in class SDL::Base::Type::ImmediateBooking.
broker_1        | W, [2015-04-08T09:29:34.705333 #27469]  WARN -- : Overwriting existing field identifier in class SDL::Base::Type::SynchronousBooking.
broker_1        | I, [2015-04-08T09:29:34.710032 #27469]  INFO -- : Loaded compendium.
broker_1        | W, [2015-04-08T09:29:35.416532 #27469]  WARN -- :   MOPED: Could not resolve IP for: mongodb:27017 runtime: n/a
broker_1        | W, [2015-04-08T09:29:35.417257 #27469]  WARN -- :   MOPED: Retrying connection attempt 1 more time(s). runtime: n/a
broker_1        | W, [2015-04-08T09:29:35.671875 #27469]  WARN -- :   MOPED: Could not resolve IP for: mongodb:27017 runtime: n/a

**Comment by cblanchet** [comment]
When I run the docker-compose command, I get the following error (on a CentOS system).

Building broker...
Step 0 : FROM dockerfile/ubuntu
 ---> b87155bee962
Step 1 : RUN gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3 &&    curl -sSL https://get.rvm.io | bash -s stable --ruby=2.1 &&    /bin/bash -c "source /usr/local/rvm/scripts/rvm && gem install passenger"
 ---> Using cache
 ---> 88992a3c2a17
Step 2 : ADD . /root/tresor-broker
 ---> Using cache
 ---> 015aaf65da00
Step 3 : WORKDIR /root/tresor-broker
 ---> Using cache
 ---> b319efbdd786
Step 4 : RUN /bin/bash -c "source /usr/local/rvm/scripts/rvm && bundle install && rake assets:precompile"
 ---> Running in 7079e5f00169
/bin/bash: bundle: command not found
Service 'broker' failed to build: The command [/bin/sh -c /bin/bash -c "source /usr/local/rvm/scripts/rvm && bundle install && rake assets:precompile"] returned a non-zero code: 127

**Comment by ilke-zilci** [comment]
See TU-Berlin-SNET/tresor-tracking#1
