### ISSUE TITLE
website preview

### ISSUE THREAD

**Issue by mathiasslawik** [cyclone-project/cyclone-tracking#7]
As a CYCLONE consortium member I want to access the preview version of the website.

**Comment by mathiasslawik** [comment]
The preview website is available: http://cyclone-project.github.io/

**Comment by lodygens** [comment]
Well done :)

**Comment by mathiasslawik** [comment]
Thanks. I've updated the page with a news section, post template, discussions and adjusted the partner logo sizes for mobile devices.

**Comment by eduesc** [comment]
Some comments:
- I think we'll also need to put the H2020 and EC logos somewhere in the
main page.
- Can the news in the main page show a preview of the contents? (one or two
lines)
- I tried to log in to comment on the news and it didn't seem to work for
me with a google account

---
Eduard Escalona, PhD
Area Director
Distributed Applications and Networks Area (DANA)
i2CAT Foundation, Barcelona, Spain
Tel: +34 93 553 2518 - http://dana.i2cat.net

**Comment by lodygens** [comment]
Some type error:
http://cyclone-project.github.io/2015/02/10/first-planning-meeting.html
  'fist agile planning meeting' -> fiRst

http://cyclone-project.github.io/consortium.html
  'SixSq Sàrl' -> SixSq Sarl

:)

**Comment by ydemchen** [comment]
Preview is good, agree with Eduard's comments.
Also partners with long descriptions need to review their description and reduce them to the size of SixSq and TUB.

**Comment by mathiasslawik** [comment]
The Sàrl stands for "Société à responsabilité limitée", so the à stands for à. ;-)

**Comment by mathiasslawik** [comment]
I'll add a footer with the EC H2020 logo.

**Comment by lodygens** [comment]
no this is "Societe Anonyme � Responsabilit� Limit�e"
:)


Oleg Lodygensky
Laboratoire de l'Accelerateur Lineaire
Universite Paris Sud 11
Bat 200
91898 Orsay Cedex
France

T�l +33 (0)1 64 46 82 75
Mobile +33 (0)6 52 85 71 21
Fax +33 (0)1 69 07 94 04
email : oleg.lodygensky@lal.in2p3.fr
Web : http://www.xtremweb-hep.org



Le 13 f�vr. 2015 � 09:22, Mathias Slawik <notifications@github.com> a �crit :

**Comment by loomis** [comment]
Not in Switzerland. 

Cal

**Comment by lodygens** [comment]
ah ok

Oleg Lodygensky
Laboratoire de l'Accelerateur Lineaire
Universite Paris Sud 11
Bat 200
91898 Orsay Cedex
France

Tél +33 (0)1 64 46 82 75
Mobile +33 (0)6 52 85 71 21
Fax +33 (0)1 69 07 94 04
email : oleg.lodygensky@lal.in2p3.fr
Web : http://www.xtremweb-hep.org

**Comment by mathiasslawik** [comment]
Please see the updated version.

**Comment by lodygens** [comment]
I see come corrections 
:)

By the way, I wonder if all deliverables are public; we should check that the website only lists public deliverables.
:)

**Comment by mathiasslawik** [comment]
I've only put the public deliverables on the website, i.e., excluded the semester reports for example.

**Comment by lodygens** [comment]
great

**Comment by lodygens** [comment]
Please replace (CNRSNational Centre for Scientific Research http://www.cnrs.fr) by (National Centre for Scientific Research http://www.cnrs.fr)

**Comment by qshacker** [comment]
Please change QSC to QSC AG in Navigation space 

http://cyclone-project.github.io/consortium.html

**Comment by mathiasslawik** [comment]
OK

**Comment by mathiasslawik** [comment]
I've fixed the affix not working. It was a bug on the side of Bootstrap: https://github.com/twbs/bootstrap/issues/15032

**Comment by eduesc** [comment]
Preview successfully presented
