### ISSUE TITLE
Discuss website analytics tool

### ISSUE THREAD

**Issue by ilke-zilci** [cyclone-project/cyclone-tracking#77]
In order to track the KPI number of visitors

**Comment by mathiasslawik** [comment]
We should not use Google Analytics

They have breached European data privacy laws in the past and they still do not provide a detailed description how the collected data is used.

I think we should use either Open Source or European web analytics companies products to adhere to European data privacy laws, see http://webanalyticsalliance.eu/.

I could set up a private piwik instance at TUB, but we would need to have a privacy policy if we start collecting users data. Can Interoute provide a legally correct privacy policy?

I don't want to be liable in case anyone sues us.

**Comment by mathiasslawik** [comment]
Integrated Piwik on the website, hosted by TUB in Berlin.
