### ISSUE TITLE
Add contact form to the website

### ISSUE THREAD

**Issue by ilke-zilci** [cyclone-project/cyclone-tracking#78]
options: use third party service vs. host a script on TUB.

**Comment by ilke-zilci** [comment]
decided to use a third party service.

**Comment by ilke-zilci** [comment]
Contact form on the feat/form branch of cyclone-project.github.io.

**Comment by mathiasslawik** [comment]
Without having a lawful privacy statement, you could change the form to redirect the user to the URL: "mailto:contact@cyclone-project.eu?subject=<subject from form>&body=<body from form>". It instructs the user agent to try to send an email to our official contact mail "contact@cyclone-project.eu".

**Comment by ilke-zilci** [comment]
merged the feat/form to master, so now we have a contact from which prepopulates the email in the users email client.
