### ISSUE TITLE
public website available

### ISSUE THREAD

**Issue by mathiasslawik** [cyclone-project/cyclone-tracking#8]
As a member of the general public I want to access the project website under http://www.cyclone-project.eu

**Comment by mathiasslawik** [comment]
I've cleared with OVH how we can procure the domain and started the TUB procurement process. The domain should be available in 1 - 2 weeks.

**Comment by eduesc** [comment]
We can use this ticket to also discuss about the contents of the first public release of the website.

**Comment by mathiasslawik** [comment]
We have successfully registered the domain and can make the website available anytime now.

**Comment by Josyab** [comment]
The official URL (www.cyclone-project.eu) it's just not pointing to the website yet.

**Comment by ilke-zilci** [comment]
The public website is available at www.cyclone-project.eu.
