### ISSUE TITLE
Deliver the MS11 (M311) – Plan for deployment and testing of selected use cases in Year 1

### ISSUE THREAD

**Issue by cblanchet** [cyclone-project/cyclone-tracking#81]

**Comment by cblanchet** [comment]
Dear all,

I integrated your comments and contribution in a new version 3.1 (available in OneDrive).

Best regards,
Christophe

**Comment by cblanchet** [comment]
version 4.0. Contributors	CNRS, TUB, IRT
Revision of use cases and common requirements. Addition of tables summarizing the major points Description of the TRESOR  components. Description of the IRT testbed facilities.

**Comment by cblanchet** [comment]
New version (v5.0) of the document with revised deployment and testing chapters, the description of the QSC testbed facilities, and update of the IRT one.

In Cyclone > WP3 > Deliverables and milestones > M311

**Comment by mathiasslawik** [comment]
The Milestone is closed.
