### ISSUE TITLE
MS11 - CNRS LAL to provide an overall description of StratusLab

### ISSUE THREAD

**Issue by cblanchet** [cyclone-project/cyclone-tracking#84]
Related to the task #81 
Provide a overall description of the software and focus on relevant point to satisfy use cases requirements
Level of maturity of the different components and availability in the testbed infrastructure

**Comment by lodygens** [comment]
where are the use cases requirements?
thanks
:)

**Comment by lodygens** [comment]
I guess this issue follows #58.
I uploaded onedrive/CYCLONE/WP7 - testbed/M7.1/CYCLOE_M7.1_v1.1-lal.docx.
Hope this helps.

**Comment by lodygens** [comment]
You mean a descirption of the middleware?

Is there any document in onedrive or should I write only here?

BTW, the stratuslab middleware is decribed here: http://stratuslab.readthedocs.org/en/latest/

Here it is in a single paragraph:

StratusLab provides a complete, open source cloud distribution, allowing the installation of public or private “Infrastructure as a Service” cloud infrastructures. It aims to be both simple to use and simple to install.

Cloud infrastructures provide many benefits to developers and end-users (scientists and engineers). End-users appreciate the cloud’s ability:
- to provide a customized execution environment,
- to make available pre-installed and pre-configured applications,
- to provision new resources (CPU, storage, etc.) rapidly, and
- to allow complete control of those resources.

Application and service developers also appreciate:
- easy access to the services through simple APIs and
 - the elasticity of the cloud to respond to peaks in demand.

StratusLab provides a couple mechanisms for accessing cloud resources: a command line interface written in portable python and web interfaces (for a subset of services). Developers can also use the Libcloud API, the StratusLab Python API, or the service REST APIs for programmatic access.

**Comment by cblanchet** [comment]
CNRS provided the required contribution
