### ISSUE TITLE
MS11 - TUB to provide an overall description of TRESOR

### ISSUE THREAD

**Issue by cblanchet** [cyclone-project/cyclone-tracking#86]
Related to the task #81 
Provide a overall description of the software and focus on relevant point to satisfy use cases requirements
Level of maturity of the different components and availability in the testbed infrastructure

**Comment by mathiasslawik** [comment]
I do not know how to satisfy use case requirements, as the requirements are missing some information. I created the tasks #104, #106 and #109 to reflect this.

Specifically I need to know how the use case itself should be deployed (e.g. the portal, etc.) to know where and how to deploy TUB components ( #104 ). I also need more information on the communication protocols ( #106 ) to know, how to deploy TCTP. At last, I need more information about the authorization aspects of the use case ( #109 ) to see how to deploy the policy management.

**Comment by mathiasslawik** [comment]
There is enough information now so that I could fill the respective section in the document.

I've created a new version CYCLONE_MS11-v3.2-TUB.docx

I'll close this ticket. Please reopen if there are any issues with the contribution.

**Comment by cblanchet** [comment]
Thanks for the contribution
