### ISSUE TITLE
lead the discussion on website content

### ISSUE THREAD

**Issue by mathiasslawik** [cyclone-project/cyclone-tracking#9]
As a cyclone consortium member I want to participate in the creation of the website.

**Comment by lodygens** [comment]
Public communication channels (web site, twitter etc.) should only publish public informations (e.g. nothing about internal organization such as project meeting)
:)

**Comment by mathiasslawik** [comment]
I've pushed some changes to our website.

These are the current things to discuss:
* General feedback on content and structure.
* Are the key messages on the front page suitable? I was inspired by the "Target Communities and Messages" in D2.1
* What news do we want to publish on the website? Do we want to publish the same or different news on the twitter feed?
* Do we want to shorten the "About" section?
* I've linked all "CYCLONE"-enabled software on the "Software" page. Please check the text. Also - I did not find much information about GAAA-TK and SNE-XACML. Could UvA provide this?
* I've put in a rudimentary press section. How do we get "press-suitable" content for this?
* We need a lawful imprint. I've done this for my personal webpage but am unsure, how this should look like for our project page. Any ideas?

**Comment by lodygens** [comment]
Concerning the web site itself:
- globally, the site is not bad at all
But:
- modern design uses kind of one page with big paragraph (e.g. https://bitnami.com, discussed below)
- about page is too long;
- consortium page: the IFB logo is missing;
- software page is empty;
- press page content will grow as we produce press article :)

Concerning software dissimination.
If we want to dessiminate the software, we should have something that looks very simple. For this simplicity, I like very much the Bitnami web site (https://bitnami.com) where the first page contains a few powerfull head lines separated in easily visible paragraphs:
- one word presentation (1M users etc)
- one happy user feedback
- "run anywhere"
- "one click deployment"
etc.

Concerning communication channels like twitter:
- I guess tweets should contain powerfull head line only with a link to the project news page
:)

Hope this helps,
Oleg

**Comment by mathiasslawik** [comment]
I've uploaded some missing files. I've forgot to git add them - must be the flu. :cold_sweat:

If you find the webpage "not bad at all" we could launch it as-is and make a second version in the following months, as it depends on content not yet ready, e.g., the flyer or very short software overview texts.

**Comment by Josyab** [comment]
Hi Mathias, all,

Today during the meeting we agreed that ALL partners will take a look on
the current shape and content (also considering your previous bullet
points) and provide eedback on it.
I propose to provide this feedback and launch a "clean" version by the end
of this week or early next week.
I personally find it quite in a good shape, but I would like to take a
deeper look on it, just in case :)

Bests,
Jose

2015-03-04 15:22 GMT+01:00 Mathias Slawik <notifications@github.com>:

> I've uploaded some missing files. I've forgot to git add them - must be
> the flu. [image: :cold_sweat:]
>
> If you find the webpage "not bad at all" we could launch it as-is and make
> a second version in the following months, as it depends on content not yet
> ready, e.g., the flyer or very short software overview texts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclone-project/cyclone-tracking/issues/9#issuecomment-77165611>
> .
>



-- 
---
José Ignacio Aznar
Distributed Applications and Networks Area (DANA)
i2CAT Foundation, Barcelona, Spain
http://dana.i2cat.net

<http://dana.i2cat.net/>   <http://www.i2cat.net/en>
----------------------------------------------------------
The information contained in this electronic mail message is confidential.
It is intended solely for the use of the individual or entity to whom it is
addressed and others authorised to receive it. If the reader of this
message is not the intended recipient, you are hereby notified that any
use, copying, dissemination or disclosure of this  information is strictly
prohibited. If you receive this e-mail message in error please notify me
immediately at the address box jose.aznar@i2cat.net
---------------------------------------------------------

**Comment by mathiasslawik** [comment]
No problem. If the flu goes back, I'll be in the office on monday.

If there are some issues, we should differentiate between "before go-live" and "after go-live".

**Comment by Josyab** [comment]
Hi there, 

Some additional comments:

Home tab : 
1.- Add the "follow us in Linkedin"? Twitter is there, i would also include linkedin.
2.- "Contact us" Tab to receive feedback and questions, suggestion could be included.

About tab: 
1.-Maybe include some additional images and shorten the text of the "about" tab. It looks too heavy IMHO.

**Comment by ydemchen** [comment]
First, general comments as requested by Mathias. 

* General feedback on content and structure.
At this stage we need to make a first consistent version, even if content is not perfect. Need just to provide a general structure and prepare for production work.

1) remove new related to submission and approval, start from kick-off meeting
2) consortium page is OK
3) I would not place deliverable table as a whole.
Let's keep it until we have second deliverable and after that place only delivered deliverable.
4) Software page looks good but we need still to clear distinguish between available, improved and new developed software
About GAAA-TK and SNE-XACML, links will be provided shortly.
5) Page Press - idea is good but need to make real content and in English at least short summary


* Are the key messages on the front page suitable? I was inspired by the "Target Communities and Messages" in D2.1

1) messages to all -> change to messages to Developers and Practitioners 
2) change sequence to: Provider - Developer - Other projects

* What news do we want to publish on the website? Do we want to publish the same or different news on the twitter feed?

1) website news need to be announced on Twitter but we should have a separate TWitter strip - however I would make it narrower than now.

* Do we want to shorten the "About" section?

It should hierarchical with short one screen text with links to 
* Objectives
* Software
* Partners
* etc

* I've linked all "CYCLONE"-enabled software on the "Software" page. * Please check the text. Also - I did not find much information about GAAA-TK and SNE-XACML. Could UvA provide this?

As I mentioned it should be to clear distinguish between available, improved and new developed software
About GAAA-TK and SNE-XACML, links will be provided shortly.

* I've put in a rudimentary press section. How do we get "press-suitable" content for this?

Actually, I don't know if we need both News and Press.
Will listen others.

* We need a lawful imprint. I've done this for my personal webpage but am unsure, how this should look like for our project page. Any ideas?

Current looks acceptable.
Maybe just call it Colophon  and Copyright?

------
Agree with Jose below.
