### ISSUE TITLE
Make tutorials available in the Website

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-tracking#95]
As a User I would like to be able to consult the available tutorial slides in the Website. First, it must be created the proper place in the website to host them. Once this has been done, TUB, UvA, i2CAT and LAL should be putting their slides there

**Comment by ilke-zilci** [comment]
Tutorials are now under the Media tab. To add others, put the file in the assets/images/tutorials folder and provide a link to it in the tutorials.md file.
[XXX Tutorial](/assets/images/tutorials/XXX_Tutorial.pdf)

**Comment by lodygens** [comment]
Stratuslab tutorials available on the web site.
Thanks

**Comment by Josyab** [comment]
Also OpenNaaS tutorial is available

**Comment by ilke-zilci** [comment]
all tutorials available online.
