### ISSUE TITLE
Plan next 5 months of work in detail

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-tracking#96]
As a user I would like to know the specific steps and milestones that reflect the work plan for the next months until M10, when the CYCONE consortium will be providing the first showcasing.

**Comment by Josyab** [comment]
The work plan from M6 to M10 has been uploaded to OneDrive (https://onedrive.live.com/redir?resid=2c3033fe409659bd!403&authkey=!AOfrsLMMe98Azj4&v=3&ithint=photo%2cpng). It will be explained during the Sprint 5 Planning meeting the 4th of June.

**Comment by lodygens** [comment]
dear Jose,
do you need a « rendezvous » room ?

cheers


Oleg Lodygensky
Laboratoire de l'Accelerateur Lineaire
Universite Paris Sud 11
Bat 200
91898 Orsay Cedex
France

Tél +33 (0)1 64 46 82 75
Mobile +33 (0)6 52 85 71 21
Fax +33 (0)1 69 07 94 04
email : oleg.lodygensky@lal.in2p3.fr
Web : http://www.xtremweb-hep.org

**Comment by Josyab** [comment]
Hi Oleg,

Yes please! Could you please provide it?
Thanks a lot!
Best Regards,
Jose

2015-06-04 9:21 GMT+02:00 Oleg Lodygensky <notifications@github.com>:

> dear Jose,
> do you need a « rendezvous » room ?
>
> cheers
>
>
> Oleg Lodygensky
> Laboratoire de l'Accelerateur Lineaire
> Universite Paris Sud 11
> Bat 200
> 91898 Orsay Cedex
> France
>
> Tél +33 (0)1 64 46 82 75
> Mobile +33 (0)6 52 85 71 21
> Fax +33 (0)1 69 07 94 04
> email : oleg.lodygensky@lal.in2p3.fr
> Web : http://www.xtremweb-hep.org
>
>
>
> > Le 3 juin 2015 à 16:23, José Aznar <notifications@github.com> a écrit :
> >
> > The work plan from M6 to M10 has been uploaded to OneDrive (
> https://onedrive.live.com/redir?resid=2c3033fe409659bd!403&authkey=!AOfrsLMMe98Azj4&v=3&ithint=photo%2cpng).
> It will be explained during the Sprint 5 Planning meeting the 4th of June.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclone-project/cyclone-tracking/issues/96#issuecomment-108763680>
> .
>



-- 
---
José Ignacio Aznar
Distributed Applications and Networks Area (DANA)
i2CAT Foundation, Barcelona, Spain
http://dana.i2cat.net

<http://dana.i2cat.net/>   <http://www.i2cat.net/en>
----------------------------------------------------------
The information contained in this electronic mail message is confidential.
It is intended solely for the use of the individual or entity to whom it is
addressed and others authorised to receive it. If the reader of this
message is not the intended recipient, you are hereby notified that any
use, copying, dissemination or disclosure of this  information is strictly
prohibited. If you receive this e-mail message in error please notify me
immediately at the address box jose.aznar@i2cat.net
---------------------------------------------------------

**Comment by lodygens** [comment]
https://rendez-vous.renater.fr/cyclone

:)



Oleg Lodygensky
Laboratoire de l'Accelerateur Lineaire
Universite Paris Sud 11
Bat 200
91898 Orsay Cedex
France

Tél +33 (0)1 64 46 82 75
Mobile +33 (0)6 52 85 71 21
Fax +33 (0)1 69 07 94 04
email : oleg.lodygensky@lal.in2p3.fr
Web : http://www.xtremweb-hep.org

**Comment by lodygens** [comment]
is it not supposed to be now ???
:)

Oleg Lodygensky
Laboratoire de l'Accelerateur Lineaire
Universite Paris Sud 11
Bat 200
91898 Orsay Cedex
France

Tél +33 (0)1 64 46 82 75
Mobile +33 (0)6 52 85 71 21
Fax +33 (0)1 69 07 94 04
email : oleg.lodygensky@lal.in2p3.fr
Web : http://www.xtremweb-hep.org
